server:
  port: 9002

spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-remote}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: dbo

  data:
    redis:
      port: 6379
      timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,resilience4j.circuitbreakers
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true


redis:
  service:
    prefix: "stofina:userservice:"
    ttl:
      activation: 86400
      reset: 1800
      refresh: 604800

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      mailService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      mailService:
        max-attempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
