app:
  url: http://localhost:3000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:sqlserver://${PROD_DB_HOST};databaseName=Troya;encrypt=true;trustServerCertificate=true
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  data:
    redis:
      host: redis

security:
  jwt:
    secret: "${JWT_SECRET}"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
