app:
  url: http://localhost:3000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost};databaseName=Troya;encrypt=true;trustServerCertificate=true
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

security:
  jwt:
    secret: ${JWT_SECRET:7A74h6Ne+6Dw2EQZ0VL7YpTeLYYa6iZ9Z3dJq1LC3Yg=}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:${EUREKA_URL:http://localhost:8761/eureka}

