global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3100']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3200']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:9002']

  - job_name: 'portfolio-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['portfolio-service:9001']

  - job_name: 'market-data-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['market-data-service:9005']

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:9006']

  - job_name: 'mail-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['mail-service:9004']

  - job_name: 'customer-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['customer-service:9003']
