server:
  port: 9005
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-remote}
  application:
    name: market-data-service

  jpa:
    show-sql: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false


market:
  update-interval-ms: 10000
  max-change-percent: 0.02
  daily-limit-percent: 0.10

cache:
  price-ttl-seconds: 5
  session-ttl-seconds: 3600
  stats-ttl-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

