spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:sqlserver://${PROD_DB_HOST};databaseName=Troya;encrypt=true;trustServerCertificate=true
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDIS_HOST}
      port:  ${REDIS_PORT}
      timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

security:
  jwt:
    secret: "${JWT_SECRET}"