server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-remote}
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.web.cors.reactive: DEBUG
    reactor.netty.http.server: DEBUG
    com.stofina.app.apigateway: DEBUG
